# How

`numpy` is a large library with incredible functionality all of which will not be
listed here. Instead some specific tools will be described so as to give a
sufficient understanding of the capabilities of the library.

## How to create an array

To create a `numpy` array we use the `numpy.array` tool which takes any iterable.

````{tip}
```
numpy.array(iterable)
```
````

For example:

In [1]:
import numpy as np

array = np.array((0, 12, 3, 1))
array

array([ 0, 12,  3,  1])

## How to create a given number of values between two bounds

`numpy` has a popular tool to create a linear space: `numpy.linspace` which take
a lower bound, an upper bounds and a number. It returns the given number of points
uniformly spaced between the bounds.

````{tip}
```
numpy.linspace(lower_bound, upper_bound, number)
```
````

For example:

In [2]:
import numpy as np

np.linspace(10, 400, 4)

array([ 10., 140., 270., 400.])

## How to create an array of zeros

To create an array of zeros we can use the `numpy.zeros` tool. It takes an
argument for the dimension of the array. This can either be a single number in
which case a single dimensional array is created or a tuple with multiple
dimensions.

````{tip}
```
numpy.zeros(size)
```
````

For example:

In [3]:
import numpy as np

np.zeros(4)

array([0., 0., 0., 0.])

Or:

In [4]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## How to generate random arrays

`numpy` has a powerful random number generator. It can be accessed from
`numpy.random` and has multiple tools. The simplest of which is
`numpy.random.random`. This takes an optional argument that is the dimension of
the array.

````{tip}
```
numpy.random.random(size)
```
````

For example:

In [5]:
import numpy as np

np.random.random()

0.4587724633937197

Or:

In [6]:
import numpy as np

np.random.random((3, 5))

array([[0.76967004, 0.66152064, 0.3592972 , 0.00684484, 0.7730941 ],
       [0.56947477, 0.09754047, 0.49804531, 0.71259094, 0.29393106],
       [0.01084657, 0.34166534, 0.30369954, 0.19422252, 0.09834434]])

## How to index arrays

Multiple dimensional arrays can be indexed in a natural mathematical way using
`array[position]`.

````{tip}
```
array[position]
```
````

For example:

In [7]:
import numpy as np

array = np.array(((1, 2, 3), (4, 5, 6)))
array[1, 2]

6

## How to do arithmetic on arrays

It is possible to directly do arithmetic on arrays in a mathematical way.

````{tip}
```
array1 + array2
```
````

For example to do element wise multiplication:

In [8]:
array1 = np.array((1, 2, 3, 4))
array2 = np.array((2, 0, -1, 0.5))
array1 * array2

array([ 2.,  0., -3.,  2.])

## How to invert a matrix

`numpy` can invert a matrix using `np.linalg.inv`. There are numerous other
linear algebraic tools available in `np.linalg`.

````{tip}
```
np.linalg.inv(array)
```
````

For example:

In [9]:
import numpy as np

matrix = np.array(((1, 2), (3, 1)))
matrix_inverse = np.linalg.inv(matrix)
matrix_inverse

array([[-0.2,  0.4],
       [ 0.6, -0.2]])

We can confirm the expected result:

In [10]:
matrix @ matrix_inverse

array([[1., 0.],
       [0., 1.]])

## How to raise a matrix to a power

Using the usual operator for exponentiation `**` with a `numpy` array carries
out element wise exponentiation. To raise a matrix to a power we use
`np.linalg.matrix_power`. This takes an array and the exponent.

````{tip}
```
np.linalg.ing(array, exponent)
```
````

For example:

In [11]:
import numpy as np

matrix = np.array(((1, 2), (3, 1)))
np.linalg.matrix_power(matrix, 3)

array([[19, 18],
       [27, 19]])

## How to fit a line of best fit

`numpy` can be used to fit polynomials to a points. This is done with the
`numpy.polyfit` tool. This takes an array of x values, an array of y values and
a degree. It returns the coefficients of a polynomial of given degree that best
approximates $f(x)=y$.

````{tip}
```
np.polyfit(x, y, degree)
```
````

For example, the code below creates `y` using a quadratic and recovers the
coefficients of the quadratic:

In [12]:
x = np.array((1, 2, 3, 4))
y = 2 * x ** 2 + 3 * x + 1
a, b, c = np.polyfit(x, y, 2)
a, b, c

(1.9999999999999993, 3.0000000000000044, 1.000000000000003)