Questions about matrices and simultaneous equations taken from https://alevelmathsrevision.com/downloads/Y2%20Further/Pure/Matrices,%20Simultaneous%20Equations%20and%20Applications%20to%20Intersections%20of%20Planes%20Exam%20Questions.pdf

Q1 The matrix \\(D\\) is given by \\(D = \begin{pmatrix} a & 2 & 0\\ 3 & 1 & 2\\ 0 & -1 & 1\end{pmatrix}\\) where \\(a\ne 2\\).

1. Find \\(D^{-1}\\).
2. Hence of otherwise, solve the equations:

    \\[
    \begin{array}
        ax + 2y = 3\\
        3x + y + 2z = 4\\
        - y + z = 1\\
    \end{array}
    \\]

In [2]:
import sympy as sym

a = sym.Symbol("a")
D = sym.Matrix([[a, 2, 0], [3, 1, 2], [0, -1, 1]])
D

Matrix([
[a,  2, 0],
[3,  1, 2],
[0, -1, 1]])

In [5]:
D.inv()

Matrix([
[-9/(18 - 9*a), 6/(18 - 9*a),    -12/(18 - 9*a)],
[  3/(6 - 3*a), -a/(6 - 3*a),     2*a/(6 - 3*a)],
[ -3/(3*a - 6),  a/(3*a - 6), (a - 6)/(3*a - 6)]])

In [7]:
b = sym.Matrix([[3], [4], [1]])
b

Matrix([
[3],
[4],
[1]])

In [26]:
sym.simplify(D.inv() @ b)

Matrix([
[        5/(3*(a - 2))],
[(2*a - 9)/(3*(a - 2))],
[5*(a - 3)/(3*(a - 2))]])

In [27]:
sym.simplify(D @ D.inv() @ b)

Matrix([
[3],
[4],
[1]])

In [28]:
import numpy as np

In [29]:
A = np.array(D.subs({a: 3})).astype(np.float64)
A

array([[ 3.,  2.,  0.],
       [ 3.,  1.,  2.],
       [ 0., -1.,  1.]])

In [30]:
np.linalg.inv(A)

array([[ 1.        , -0.66666667,  1.33333333],
       [-1.        ,  1.        , -2.        ],
       [-1.        ,  1.        , -1.        ]])

In [31]:
c = np.array([[3], [4], [1]])
np.linalg.inv(A) @ c

array([[ 1.66666667],
       [-1.        ],
       [ 0.        ]])

Q3 

The matrix \\(A\\) is given by \\(A=\begin{pmatrix}a & 1 & 1\\ 1 & a & 1\\ 1 & 1 & 2\end{pmatrix}\\).

1. Find the determinant of \\(A\\)
2. Hence find the values of \\(a\\) for which \\(A\\) is singular.

In [33]:
A = sym.Matrix([[a, 1, 1], [1, a, 1], [1, 1, 2]])
A.det()

2*a**2 - 2*a

In [34]:
sym.solveset(A.det(), a)

FiniteSet(0, 1)

In [38]:
A.subs({a: 0}).inv()

NonInvertibleMatrixError: Matrix det == 0; not invertible.

In [37]:
A.subs({a: 1}).inv()

NonInvertibleMatrixError: Matrix det == 0; not invertible.